# -*- coding: utf-8 -*-
"""LIF_Neuron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/NeuroSamDeb/My-models-of-Neuron/blob/main/LIF/LIF_Neuron.ipynb
"""

# This is a small model of a LIF neuron

import numpy as np
import matplotlib.pyplot as plt

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
            refractory_counter -= 1
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args) # args contains the rest of the arguments of the ODE
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Parameters for the LIF Neuron Model
k = -60.0    # Membrane resting potential (mV)
y0 = -70.0   # Initial membrane potential (mV)
t_start = 0.0  # Start time (ms)
t_end = 200.0  # End time (ms)
h_val = 0.1    # Step size for Euler method (ms)
a = 10.0     # Membrane time constant (ms)
R = 10.0     # Membrane resistance (MOhms)
I = 3.0      # Injected current (nA) - Increased for spiking

u_threshold = -50.0 # Spike threshold (mV)
u_reset = -70.0   # Reset potential after spike (mV)
refractory_period = 2.0 # Refractory period (ms)
refractory_period_steps = int(refractory_period / h_val)

# Solve using Euler method with LIF spiking logic
t_euler, u_euler, spike_times = euler_method_lif(
    dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
)

# Plot the results
plt.figure(figsize=(12, 6))
plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

# Plot spikes as vertical lines
for spike_time in spike_times:
    plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

# Plot threshold and reset lines
plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

plt.title('Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane Potential (mV)')
plt.legend()
plt.grid(True)
plt.show()

"""This is an example of a LIF neuron model, based upon the concept of the neuronal membrane being modeled as a circuit with two paths for current flow across the potential difference of the cell membrane.

one path (Path 1) is through a capacitor C, exemplifying the lipid bilayer chemistry of the neuron membrane. Another path (Path 2) is through a resistance and a battery in series, representing the effect of ion channels and pumps in the cell membrane.

Another condition is also the firing time condition, which signifies the neuron's primary role to 'fire' a spike just as the potential crosses a certain limit, after which the membrane returns to resting potential.
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
            refractory_counter -= 1
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args)
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Parameters for the LIF Neuron Model
k = -60.0    # Membrane resting potential (mV)
y0 = -70.0   # Initial membrane potential (mV)
t_start = 0.0  # Start time (ms)
t_end = 200.0  # End time (ms)
h_val = 0.1    # Step size for Euler method (ms)
a = 10.0     # Membrane time constant (ms)
R = 30.0     # Membrane resistance (MOhms)
I = 2.0      # Injected current (nA) - Increased for spiking

u_threshold = -50.0 # Spike threshold (mV)
u_reset = -70.0   # Reset potential after spike (mV)
refractory_period = 2.0 # Refractory period (ms)
refractory_period_steps = int(refractory_period / h_val)

# Solve using Euler method with LIF spiking logic
t_euler, u_euler, spike_times = euler_method_lif(
    dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
)

# Plot the results
plt.figure(figsize=(12, 6))
plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

# Plot spikes as vertical lines
for spike_time in spike_times:
    plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

# Plot threshold and reset lines
plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

plt.title('Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane Potential (mV)')
plt.legend()
plt.grid(True)
plt.show()

"""This is the same model with a different Resistance of 30 mOhms, from the previous 10 mOhms. The change, exemplified by the increased number of peaks and decreased interpeak interval, implies a decrease in current flow through the membrane through path 2."""

import numpy as np
import matplotlib.pyplot as plt

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args) # args contains the rest of the arguments of the ODE
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Parameters for the LIF Neuron Model
k = -60.0    # Membrane resting potential (mV)
y0 = -70.0   # Initial membrane potential (mV)
t_start = 0.0  # Start time (ms)
t_end = 200.0  # End time (ms)
h_val = 0.1    # Step size for Euler method (ms)
a = 10.0     # Membrane time constant (ms)
R = 10.0     # Membrane resistance (MOhms)
I = 3.0      # Injected current (nA) - Increased for spiking

u_threshold = -50.0 # Spike threshold (mV)
u_reset = -70.0   # Reset potential after spike (mV)
refractory_period = 2.0 # Refractory period (ms)
refractory_period_steps = int(refractory_period / h_val)

# Solve using Euler method with LIF spiking logic
t_euler, u_euler, spike_times = euler_method_lif(
    dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
)

# Plot the results
plt.figure(figsize=(12, 6))
plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

# Plot spikes as vertical lines
for spike_time in spike_times:
    plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

# Plot threshold and reset lines
plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

plt.title('Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane Potential (mV)')
plt.legend()
plt.grid(True)
plt.show()

"""This graph is due to not evolving the refractory_counter variable, making it stuck at 0 at all points in time after the first spike. Hence, this is a neuron that is permanently disabled after one spike."""

import numpy as np
import matplotlib.pyplot as plt

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
            refractory_counter -= 1
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args) # args contains the rest of the arguments of the ODE
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Parameters for the LIF Neuron Model
k = -60.0    # Membrane resting potential (mV)
y0 = -70.0   # Initial membrane potential (mV)
t_start = 0.0  # Start time (ms)
t_end = 200.0  # End time (ms)
h_val = 0.1    # Step size for Euler method (ms)
a = 30.0     # Membrane time constant (ms)
R = 10.0     # Membrane resistance (MOhms)
I = 3.0      # Injected current (nA) - Increased for spiking

u_threshold = -50.0 # Spike threshold (mV)
u_reset = -70.0   # Reset potential after spike (mV)
refractory_period = 2.0 # Refractory period (ms)
refractory_period_steps = int(refractory_period / h_val)

# Solve using Euler method with LIF spiking logic
t_euler, u_euler, spike_times = euler_method_lif(
    dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
)

# Plot the results
plt.figure(figsize=(12, 6))
plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

# Plot spikes as vertical lines
for spike_time in spike_times:
    plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

# Plot threshold and reset lines
plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

plt.title('Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane Potential (mV)')
plt.legend()
plt.grid(True)
plt.show()

"""This is the case for a or time constant being 3 times the original value, indicating a neuronal membrane where the voltage takes 3 times the time to reach 1/e of the original starting potential"""

import numpy as np
import matplotlib.pyplot as plt

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
            refractory_counter -= 1
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args) # args contains the rest of the arguments of the ODE
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Parameters for the LIF Neuron Model
k = -60.0    # Membrane resting potential (mV)
y0 = -70.0   # Initial membrane potential (mV)
t_start = 0.0  # Start time (ms)
t_end = 200.0  # End time (ms)
h_val = 0.1    # Step size for Euler method (ms)
a = 10.0     # Membrane time constant (ms)
R = 10.0     # Membrane resistance (MOhms)
I = 3.0      # Injected current (nA) - Increased for spiking

u_threshold = -50.0 # Spike threshold (mV)
u_reset = -70.0   # Reset potential after spike (mV)
refractory_period = 2.0 # Refractory period (ms)
refractory_period_steps = int(refractory_period / h_val)

# Solve using Euler method with LIF spiking logic
t_euler, u_euler, spike_times = euler_method_lif(
    dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
)

# Plot the results
plt.figure(figsize=(12, 6))
plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

# Plot spikes as vertical lines
for spike_time in spike_times:
    plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

# Plot threshold and reset lines
plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

plt.title('Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane Potential (mV)')
plt.legend()
plt.grid(True)
plt.show()

"""# Task
Add an interactive slider to cell `XHKPOG1RDGPV` for the `R` (Membrane resistance) parameter, allowing real-time visualization of its effect on the Leaky Integrate-and-Fire (LIF) neuron model.

## Add Interactive Slider for Resistance (R)

### Subtask:
Modify cell `XHKPOG1RDGPV` to include an interactive slider for the `R` (Membrane resistance) parameter, allowing real-time visualization of its effect on the Leaky Integrate-and-Fire (LIF) neuron model.

**Reasoning**:
To add an interactive slider for the 'R' parameter, I need to import ipywidgets, encapsulate the simulation and plotting logic in a function that takes 'R_val' as an argument, and then use the `interact` function to create the slider.
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact, IntSlider

# Define the differential equation for the LIF neuron membrane potential
def dudt(u, t, k, a, R, I):
    # The equation is: a * (du/dt) = -(u - k) + R * I
    # So, du/dt = (-(u - k) + R * I) / a
    return (-(u - k) + R * I) / a

# Euler method implementation with LIF spiking logic
def euler_method_lif(dudt_func, u0, t_start, t_end, h, u_threshold, u_reset, refractory_period_steps, *args):
    t = np.arange(t_start, t_end + h, h) # Time points
    u = np.zeros(len(t)) # Array to store membrane potential values
    u[0] = u0 # Initial condition

    spike_times = []
    refractory_counter = 0

    for i in range(0, len(t) - 1):
        if refractory_counter > 0:
            # During refractory period, membrane potential remains at reset value
            u[i+1] = u_reset
            refractory_counter -= 1
        else:
            # Integrate membrane potential
            du = dudt_func(u[i], t[i], *args) # args contains the rest of the arguments of the ODE
            u[i+1] = u[i] + h * du

            # Check for spike
            if u[i+1] >= u_threshold:
                spike_times.append(t[i+1])
                u[i+1] = u_reset # Reset membrane potential after spike
                refractory_counter = refractory_period_steps # Start refractory period
    return t, u, spike_times

# Function to simulate and plot with interactive R
def simulate_and_plot_lif(R_val):
    # Parameters for the LIF Neuron Model
    k = -60.0    # Membrane resting potential (mV)
    y0 = -70.0   # Initial membrane potential (mV)
    t_start = 0.0  # Start time (ms)
    t_end = 200.0  # End time (ms)
    h_val = 0.1    # Step size for Euler method (ms)
    a = 10.0     # Membrane time constant (ms)
    R = R_val    # Membrane resistance (MOhms) - now interactive
    I = 3.0      # Injected current (nA) - Increased for spiking

    u_threshold = -50.0 # Spike threshold (mV)
    u_reset = -70.0   # Reset potential after spike (mV)
    refractory_period = 2.0 # Refractory period (ms)
    refractory_period_steps = int(refractory_period / h_val)

    # Solve using Euler method with LIF spiking logic
    t_euler, u_euler, spike_times = euler_method_lif(
        dudt, y0, t_start, t_end, h_val, u_threshold, u_reset, refractory_period_steps, k, a, R, I
    )

    # Plot the results
    plt.figure(figsize=(12, 6))
    plt.plot(t_euler, u_euler, 'r-', label='LIF Neuron Membrane Potential')

    # Plot spikes as vertical lines
    for spike_time in spike_times:
        plt.axvline(spike_time, color='gray', linestyle='--', linewidth=0.8)

    # Plot threshold and reset lines
    plt.axhline(u_threshold, color='green', linestyle=':', label='Threshold Voltage')
    plt.axhline(u_reset, color='blue', linestyle=':', label='Reset Voltage')

    plt.title(f'Leaky Integrate-and-Fire (LIF) Neuron Model with Spiking (R = {R_val} MOhms)')
    plt.xlabel('Time (ms)')
    plt.ylabel('Membrane Potential (mV)')
    plt.legend()
    plt.grid(True)
    plt.show()

# Create the interactive slider for R_val
interact(simulate_and_plot_lif, R_val=(1.0, 50.0, 1.0));

"""The task was to add an interactive slider for the `R` (Membrane resistance) parameter to cell `XHKPOG1RDGPV` to visualize its effect on the Leaky Integrate-and-Fire (LIF) neuron model. This was successfully completed.

### Data Analysis Key Findings
*   The existing Leaky Integrate-and-Fire (LIF) neuron model simulation and plotting logic was refactored into a new function, `simulate_and_plot_lif`, which accepts `R_val` as an argument.
*   The `R` (Membrane resistance) parameter within the LIF model was made dynamic, controlled by the `R_val` passed to the `simulate_and_plot_lif` function.
*   An interactive slider for `R_val` was implemented using `ipywidgets.interact`, allowing users to adjust the resistance between 1.0 and 50.0 MOhms in steps of 1.0.
*   The integration of the slider enables real-time visualization of how changes in membrane resistance affect the neuron's membrane potential and spiking behavior.
"""